#!/usr/bin/env python3
"""Render the Homebrew formula and the Scoop manifest for a DRE release.

    package_managers.py <version> <SHA256SUMS of that release> <out dir>

Writes <out dir>/dre.rb (for get-dre/homebrew-tap, Formula/dre.rb) and <out dir>/dre.json
(for get-dre/scoop-bucket, bucket/dre.json). Both download the release's own archives, with
the checksums from its SHA256SUMS; both install `dre` only, since `dre` installs plugins itself.
"""

import json
import pathlib
import sys

REPO = "get-dre/dre"
DESC = "Declarative Reporting Engine: SQL in, formatted files out"
HOMEPAGE = f"https://github.com/{REPO}"
LICENSE = "GPL-3.0-only"


def sums(path):
    out = {}
    for line in pathlib.Path(path).read_text().splitlines():
        parts = line.split()
        if len(parts) == 2:
            out[parts[1].lstrip("*")] = parts[0].lower()
    return out


def asset(version, platform, ext, checksums):
    name = f"dre-{version}-{platform}.{ext}"
    if name not in checksums:
        sys.exit(f"SHA256SUMS has no {name}")
    return f"https://github.com/{REPO}/releases/download/v{version}/{name}", checksums[name]


def formula(version, checksums):
    def block(platform):
        url, sha = asset(version, platform, "tar.gz", checksums)
        return f'      url "{url}"\n      sha256 "{sha}"'

    return f'''# Generated by DRE's release workflow (.github/scripts/package_managers.py); don't edit.
class Dre < Formula
  desc "{DESC}"
  homepage "{HOMEPAGE}"
  version "{version}"
  license "{LICENSE}"

  on_macos do
    on_arm do
{block("macos-aarch64")}
    end
    on_intel do
{block("macos-x86_64")}
    end
  end

  on_linux do
    on_arm do
{block("linux-aarch64")}
    end
    on_intel do
{block("linux-x86_64")}
    end
  end

  def install
    bin.install "dre"
  end

  test do
    assert_match version.to_s, shell_output("#{{bin}}/dre --version")
  end
end
'''


def manifest(version, checksums):
    arch = {}
    for key, platform in (("64bit", "windows-x86_64"), ("arm64", "windows-aarch64")):
        url, sha = asset(version, platform, "zip", checksums)
        arch[key] = {"url": url, "hash": sha}
    base = f"https://github.com/{REPO}/releases/download/v$version"
    return {
        "##": "Generated by DRE's release workflow (.github/scripts/package_managers.py); don't edit.",
        "version": version,
        "description": DESC,
        "homepage": HOMEPAGE,
        "license": LICENSE,
        "architecture": arch,
        "bin": "dre.exe",
        "checkver": {"github": HOMEPAGE},
        "autoupdate": {
            "architecture": {
                "64bit": {"url": f"{base}/dre-$version-windows-x86_64.zip"},
                "arm64": {"url": f"{base}/dre-$version-windows-aarch64.zip"},
            },
            "hash": {"url": f"{base}/SHA256SUMS"},
        },
    }


def main(version, sums_path, out):
    checksums = sums(sums_path)
    out = pathlib.Path(out)
    out.mkdir(parents=True, exist_ok=True)
    (out / "dre.rb").write_text(formula(version, checksums))
    (out / "dre.json").write_text(json.dumps(manifest(version, checksums), indent=2) + "\n")
    print(f"wrote {out}/dre.rb and {out}/dre.json for DRE {version}")


if __name__ == "__main__":
    main(*sys.argv[1:])
