//! `dre.lock`: the exact plugin versions and package commits a project resolved, committed
//! alongside it.

use std::collections::BTreeMap;
use std::path::Path;

use semver::Version;
use serde::{Deserialize, Serialize};

use crate::project::PluginKind;

pub const LOCK_FILE: &str = "dre.lock";

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Locked {
    pub version: Version,
    pub sha256: String,
    /// Where it came from when not the default registry: `github:owner/repo` or
    /// `registry:<url>`. A different declared source re-resolves the plugin.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub from: Option<String>,
}

/// A git package pinned to the commit its declared revision resolved to.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct LockedPackage {
    pub git: String,
    pub revision: String,
    pub commit: String,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Lock {
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub sources: BTreeMap<String, Locked>,
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub formats: BTreeMap<String, Locked>,
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub destinations: BTreeMap<String, Locked>,
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub packages: BTreeMap<String, LockedPackage>,
    /// `local:` plugins by `<kind>/<name>`: the path they're used from. Nothing to pin.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub local: BTreeMap<String, String>,
}

impl Lock {
    /// The project's lock, or an empty one when there's no `dre.lock`.
    pub fn load(root: &Path) -> Result<Lock, String> {
        let p = root.join(LOCK_FILE);
        match std::fs::read_to_string(&p) {
            Ok(t) => serde_yaml_ng::from_str(&t).map_err(|e| format!("{LOCK_FILE}: {e}")),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(Lock::default()),
            Err(e) => Err(format!("{LOCK_FILE}: {e}")),
        }
    }

    pub fn save(&self, root: &Path) -> Result<(), String> {
        let body = serde_yaml_ng::to_string(self).map_err(|e| e.to_string())?;
        let text = format!(
            "# Generated by DRE: the exact plugin versions and package commits this project uses. Commit this file.\n{body}"
        );
        std::fs::write(root.join(LOCK_FILE), text).map_err(|e| format!("{LOCK_FILE}: {e}"))
    }

    fn map(&self, kind: PluginKind) -> &BTreeMap<String, Locked> {
        match kind {
            PluginKind::Source => &self.sources,
            PluginKind::Format => &self.formats,
            PluginKind::Destination => &self.destinations,
        }
    }

    pub fn map_mut(&mut self, kind: PluginKind) -> &mut BTreeMap<String, Locked> {
        match kind {
            PluginKind::Source => &mut self.sources,
            PluginKind::Format => &mut self.formats,
            PluginKind::Destination => &mut self.destinations,
        }
    }

    pub fn get(&self, kind: PluginKind, name: &str) -> Option<&Locked> {
        self.map(kind).get(name)
    }

    pub fn version(&self, kind: PluginKind, name: &str) -> Option<Version> {
        self.get(kind, name).map(|l| l.version.clone())
    }
}
